In [2]:
!pip install lifelines

Collecting lifelines
  Downloading lifelines-0.28.0-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: numpy<2.0,>=1.14.0 in /opt/conda/lib/python3.10/site-packages (from lifelines) (1.26.4)
Requirement already satisfied: scipy>=1.2.0 in /opt/conda/lib/python3.10/site-packages (from lifelines) (1.11.4)
Requirement already satisfied: pandas>=1.2.0 in /opt/conda/lib/python3.10/site-packages (from lifelines) (2.1.4)
Requirement already satisfied: matplotlib>=3.0 in /opt/conda/lib/python3.10/site-packages (from lifelines) (3.7.5)
Collecting autograd>=1.5 (from lifelines)
  Downloading autograd-1.6.2-py3-none-any.whl.metadata (706 bytes)
Collecting autograd-gamma>=0.3 (from lifelines)
  Downloading autograd-gamma-0.5.0.tar.gz (4.0 kB)
  Preparing metadata (setup.py) ... done
Collecting formulaic>=0.2.2 (from lifelines)
  Downloading formulaic-1.0.1-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: future>=0.15.2 in /opt/conda/lib/python3.10/site-packages (from autograd>=1.5->lifelines) (1.0.0)
Collecting interface-meta>=1.2.0 (from formulaic>=0.2.2->lifelines)
  Downloading interface_meta-1.3.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: typing-extensions>=4.2.0 in /opt/conda/lib/python3.10/site-packages (from formulaic>=0.2.2->lifelines) (4.9.0)
Requirement already satisfied: wrapt>=1.0 in /opt/conda/lib/python3.10/site-packages (from formulaic>=0.2.2->lifelines) (1.14.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.0->lifelines) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.0->lifelines) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.0->lifelines) (4.47.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.0->lifelines) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.0->lifelines) (21.3)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.0->lifelines) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.0->lifelines) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.0->lifelines) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.2.0->lifelines) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.2.0->lifelines) (2023.4)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.0->lifelines) (1.16.0)
Downloading lifelines-0.28.0-py3-none-any.whl (349 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 349.2/349.2 kB 8.2 MB/s eta 0:00:00:00:01
Downloading autograd-1.6.2-py3-none-any.whl (49 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 2.7 MB/s eta 0:00:00
Downloading formulaic-1.0.1-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.2/94.2 kB 6.4 MB/s eta 0:00:00
Downloading interface_meta-1.3.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: autograd-gamma
  Building wheel for autograd-gamma (setup.py) ... done
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4031 sha256=608ec4a96f733e1e6f37391bb4b7f350cb4fa206aef50f1226701658d44b61d0
  Stored in directory: /root/.cache/pip/wheels/25/cc/e0/ef2969164144c899fedb22b338f6703e2b9cf46eeebf254991
Successfully built autograd-gamma
Installing collected packages: interface-meta, autograd, autograd-gamma, formulaic, lifelines
Successfully installed autograd-1.6.2 autograd-gamma-0.5.0 formulaic-1.0.1 interface-meta-1.3.0 lifelines-0.28.0

In [42]:
import pandas as pd
import torch
import numpy as np
import math
import os

from torch import nn
import torch.nn.functional as F
from tqdm import tqdm
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from lifelines.utils import concordance_index

In [4]:
!wget https://storage.yandexcloud.net/ds-ods/files/data/docs/competitions/DataFusion2024/Data/clients.csv
!wget https://storage.yandexcloud.net/ds-ods/files/data/docs/competitions/DataFusion2024/Data/train.csv
!wget https://storage.yandexcloud.net/ds-ods/files/data/docs/competitions/DataFusion2024/Data/report_dates.csv
!wget https://storage.yandexcloud.net/ds-ods/files/data/docs/competitions/DataFusion2024/Data/transactions.csv.zip

--2024-04-25 09:18:08--  https://storage.yandexcloud.net/ds-ods/files/data/docs/competitions/DataFusion2024/Data/clients.csv
Resolving storage.yandexcloud.net (storage.yandexcloud.net)... 213.180.193.243, 2a02:6b8::1d9
Connecting to storage.yandexcloud.net (storage.yandexcloud.net)|213.180.193.243|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2457605 (2.3M) [text/csv]
Saving to: 'clients.csv'

clients.csv         100%[===================>]   2.34M  1.85MB/s    in 1.3s

2024-04-25 09:18:10 (1.85 MB/s) - 'clients.csv' saved [2457605/2457605]

--2024-04-25 09:18:11--  https://storage.yandexcloud.net/ds-ods/files/data/docs/competitions/DataFusion2024/Data/train.csv
Resolving storage.yandexcloud.net (storage.yandexcloud.net)... 213.180.193.243, 2a02:6b8::1d9
Connecting to storage.yandexcloud.net (storage.yandexcloud.net)|213.180.193.243|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 754462 (737K) [text/csv]
Saving to: 'train.csv'

train.csv           100%[===================>] 736.78K   694KB/s    in 1.1s

2024-04-25 09:18:13 (694 KB/s) - 'train.csv' saved [754462/754462]

--2024-04-25 09:18:14--  https://storage.yandexcloud.net/ds-ods/files/data/docs/competitions/DataFusion2024/Data/report_dates.csv
Resolving storage.yandexcloud.net (storage.yandexcloud.net)... 213.180.193.243, 2a02:6b8::1d9
Connecting to storage.yandexcloud.net (storage.yandexcloud.net)|213.180.193.243|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 288 [text/csv]
Saving to: 'report_dates.csv'

report_dates.csv    100%[===================>]     288  --.-KB/s    in 0s

2024-04-25 09:18:15 (30.1 MB/s) - 'report_dates.csv' saved [288/288]

--2024-04-25 09:18:16--  https://storage.yandexcloud.net/ds-ods/files/data/docs/competitions/DataFusion2024/Data/transactions.csv.zip
Resolving storage.yandexcloud.net (storage.yandexcloud.net)... 213.180.193.243, 2a02:6b8::1d9
Connecting to storage.yandexcloud.net (storage.yandexcloud.net)|213.180.193.243|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 196984122 (188M) [application/zip]
Saving to: 'transactions.csv.zip'

transactions.csv.zi 100%[===================>] 187.86M  15.8MB/s    in 13s

2024-04-25 09:18:30 (14.2 MB/s) - 'transactions.csv.zip' saved [196984122/196984122]

In [5]:
!unzip transactions.csv

Archive:  transactions.csv.zip
  inflating: transactions.csv

# Data Loading

In [6]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
os.environ["TORCH_USE_CUDA_DSA"] = "1"
device

device(type='cuda')

In [7]:
clients = pd.read_csv("clients.csv")
report_dates = pd.read_csv("report_dates.csv", parse_dates=["report_dt"])
train = pd.read_csv("train.csv")
transactions = pd.read_csv("transactions.csv", parse_dates=["transaction_dttm"])

# EDA and PreProcessing

In [8]:
clients.fillna({"employee_count_nm": 7}, inplace=True)
train.merge(clients, on="user_id").groupby("employee_count_nm").agg({"target":lambda x: [x.value_counts()[1]/len(x) * 100, x.value_counts()[1], x.value_counts()[0]]}).sort_values("target")

                                              target
employee_count_nm
БОЛЕЕ 500             [3.7065052950075645, 49, 1273]
БОЛЕЕ 1001          [4.1140837960625944, 489, 11397]
ОТ 501 ДО 1000        [4.667739710278225, 203, 4146]
ОТ 101 ДО 500         [5.491057420771886, 525, 9036]
ОТ 51 ДО 100          [5.653853976001627, 278, 4639]
ОТ 11 ДО 50           [6.507666098807496, 191, 2744]
ОТ 11 ДО 30            [7.026143790849673, 86, 1138]
ДО 10                 [7.159264931087289, 187, 2425]
ОТ 31 ДО 50             [8.135942327497425, 79, 892]
7                  [13.747264996078107, 3330, 20893]

In [9]:
clients.replace({'employee_count_nm':{'ОТ 101 ДО 500':4,'БОЛЕЕ 1001':6,'ОТ 501 ДО 1000':5,'ДО 10':0,
                                      'ОТ 11 ДО 50':2,'ОТ 51 ДО 100':3,'БОЛЕЕ 500':5,'ОТ 11 ДО 30':2,
                                      'ОТ 31 ДО 50':2}}, inplace=True)
clients.head()

/tmp/ipykernel_35/2213134391.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clients.replace({'employee_count_nm':{'ОТ 101 ДО 500':4,'БОЛЕЕ 1001':6,'ОТ 501 ДО 1000':5,'ДО 10':0,

   user_id  report  employee_count_nm  bankemplstatus  customer_age
0        3       2                  4               0             3
1        9       1                  6               0             3
2       13       6                  5               0             2
3       37       5                  6               0             2
4       41       1                  4               0             2

In [10]:
train.merge(clients, on="user_id").groupby("bankemplstatus").agg({"target":lambda x: x.value_counts()[1]/len(x) * 100})

                  target
bankemplstatus
0               8.489827
1               0.485437

Работники банка редко уходят в отток.\
Bank employees rarely churn.

In [11]:
transactions.head(5)

   user_id  mcc_code  currency_rk  transaction_amt    transaction_dttm
0        3         3            1      -183.883957 2022-01-28 12:05:33
1        3         3            1     -3206.437012 2022-01-28 12:52:30
2        3        16            1   -153866.890625 2022-02-16 14:45:56
3        3        56            1    -15144.601562 2022-03-09 19:58:29
4        3         0            1      5297.908691 2022-03-12 18:11:31

In [12]:
data = clients.merge(train, on="user_id", how="left")
data = data.merge(report_dates, on="report")

In [13]:
transactions['date'] = transactions['transaction_dttm'].dt.date.astype('datetime64[ns]')

In [14]:
transactions_upd = transactions.merge(data[["report_dt", "user_id"]], on="user_id")
transactions_upd["diff_days"] = (transactions_upd['report_dt']-transactions_upd['transaction_dttm']) / np.timedelta64(1, 'D')
some_data = transactions_upd.groupby("user_id").agg(trans_sum=("transaction_amt", "sum"),
                                                    trans_std=("transaction_amt", "std"),
                                                    trans_min=("transaction_amt", "min"),
                                                    trans_max=("transaction_amt", "max"),
                                                    trans_mean=("transaction_amt", "mean"),
                                                    trans_count=("transaction_amt", "count"),
                                                    trans_pos_sum=("transaction_amt", lambda x: x[(x>0)].sum()),
                                                    trans_neg_sum=("transaction_amt", lambda x: x[(x<0)].sum()),
                                                    trans_pos_mean=("transaction_amt", lambda x: x[(x > 0)].mean() if (x > 0).sum() > 0 else 0),
                                                    trans_neg_mean=("transaction_amt", lambda x: x[(x < 0)].mean() if (x < 0).sum() > 0 else 0),
                                                    trans_first=("transaction_amt", lambda x: x.iloc[-1]),
                                                    trans_last=("transaction_amt", lambda x: x.iloc[0]),
                                                    diff_days_max=("diff_days", "max"),
                                                    diff_days_min=("diff_days", "min"),
                                                    mcc_code_nunique=("mcc_code", "nunique"),
                                                    mcc_code_count=("mcc_code", "count"),
                                                    currency_rk_nunique=("currency_rk", "nunique"),
                                                    currency_rk_count=("currency_rk", "count"),
                                                    currency_rk_median=("currency_rk", "median"),
                                                    currency_rk_min=("currency_rk", "min"),
                                                    currency_rk_max=("currency_rk", "max"),
                                                    date_max=("date", lambda x: x.max().day),
                                                    date_min=("date", lambda x: x.min().day),
                                                    date=("date", lambda x: (x.max()-x.min()).days))

In [15]:
date_trans = transactions.groupby("user_id").agg({"date":"unique"}).explode("date").reset_index()
date_trans["interval"] = date_trans.groupby("user_id")["date"].diff()
date_trans = date_trans.dropna()
date_trans["interval"] = date_trans["interval"].dt.days
date_trans = date_trans.groupby("user_id").agg({"interval":["last","max"]})
date_trans.columns = list( map(lambda x: "date_"+str(x), date_trans.columns ) )

In [16]:
data = data.merge(some_data, on="user_id")
data = data.merge(date_trans, on="user_id")

In [17]:
data = (
                data
                .assign(hour=data.report_dt.dt.hour)
                .assign(day=data.report_dt.dt.day)
                .assign(month=data.report_dt.dt.month)
                .assign(day_of_week=data.report_dt.dt.dayofweek)
                .assign(week_of_year=data.report_dt.dt.isocalendar().week)
              )

def generate_cyclical_features(data, col_name, period, start_num=0):
    kwargs = {
        f'sin_{col_name}' : lambda x: np.sin(2*np.pi*(data[col_name]-start_num)/period),
        f'cos_{col_name}' : lambda x: np.cos(2*np.pi*(data[col_name]-start_num)/period)
             }
    return data.assign(**kwargs).drop(columns=[col_name])

data = generate_cyclical_features(data, 'hour', 24, 0)
data = generate_cyclical_features(data, 'day_of_week', 7, 0)
data = generate_cyclical_features(data, 'month', 12, 1)
data = generate_cyclical_features(data, 'week_of_year', 52, 0)

data.drop(columns=["report_dt"], inplace=True)

In [18]:
def preprocess(x):
    return (np.log(x.abs().sum()))

temp_tran = transactions.groupby(['user_id','currency_rk'])['transaction_amt'].agg([preprocess])
temp_tran = temp_tran.unstack('currency_rk').fillna(0)
temp_tran.columns = ['logsumabs_0','logsumabs_1','logsumabs_2','logsumabs_3']

In [19]:
data = data.merge(temp_tran, on="user_id")

In [20]:
data.head(3)

,user_id,report,employee_count_nm,bankemplstatus,customer_age,target,time,trans_sum,trans_std,trans_min,...,sin_day_of_week,cos_day_of_week,sin_month,cos_month,sin_week_of_year,cos_week_of_year,logsumabs_0,logsumabs_1,logsumabs_2,logsumabs_3
0,3,2,4,0,3,0.0,77.0,13706.416641,60860.880477,-153866.890625,...,0.974928,-0.222521,-5.000000e-01,-0.866025,-0.885456,-0.464723,0.00000,12.789712,0.0,0.0
1,9,1,6,0,3,NaN,NaN,-323434.666813,11797.055119,-90147.617188,...,-0.781831,0.623490,1.224647e-16,-1.000000,-0.464723,-0.885456,0.00000,12.686752,0.0,0.0
2,13,6,5,0,2,0.0,86.0,-124717.379150,23507.953991,-58740.300781,...,-0.974928,-0.222521,-5.000000e-01,0.866025,0.0,1.0,9.28478,12.825245,0.0,0.0

In [21]:
clients

       user_id  report  employee_count_nm  bankemplstatus  customer_age
0            3       2                  4               0             3
1            9       1                  6               0             3
2           13       6                  5               0             2
3           37       5                  6               0             2
4           41       1                  4               0             2
...        ...     ...                ...             ...           ...
95995   562043      12                  7               0             2
95996   562205      12                  7               0             1
95997   562312      12                  7               0             0
95998   562721      12                  7               0             2
95999   562740      12                  7               0             0

[96000 rows x 5 columns]

In [22]:
transactions

,user_id,mcc_code,currency_rk,transaction_amt,transaction_dttm,date
0,3,3,1,-183.883957,2022-01-28 12:05:33,2022-01-28
1,3,3,1,-3206.437012,2022-01-28 12:52:30,2022-01-28
2,3,16,1,-153866.890625,2022-02-16 14:45:56,2022-02-16
3,3,56,1,-15144.601562,2022-03-09 19:58:29,2022-03-09
4,3,0,1,5297.908691,2022-03-12 18:11:31,2022-03-12
...,...,...,...,...,...,...
13075018,562740,155,1,-2484.366211,2023-03-20 11:52:09,2023-03-20
13075019,562740,9,1,-187.658463,2023-03-20 12:10:22,2023-03-20
13075020,562740,1,1,-891.933350,2023-03-20 15:53:37,2023-03-20
13075021,562740,13,1,-464.467316,2023-03-20 15:54:49,2023-03-20
13075022,562740,9,1,-188.750504,2023-03-20 16:06:45,2023-03-20

In [23]:
transactions_upd["sm"] = np.where(transactions_upd['transaction_amt']<0, transactions_upd['transaction_amt'],0)
transactions_upd['sp'] = np.where( transactions_upd['transaction_amt']>0, transactions_upd['transaction_amt'],0)
transactions_upd['m'] = (transactions_upd['report_dt'].dt.year-
                     transactions_upd['transaction_dttm'].dt.year)*12+(transactions_upd['report_dt'].dt.month-
                                                                   transactions_upd['transaction_dttm'].dt.month)

msump = transactions_upd.pivot_table(values="sp",
    index="user_id",
    columns="m",
    aggfunc='sum',
    fill_value=0,)
msump.columns = list( map(lambda x: "msump"+str(x), msump.columns ) )
msump

,msump3,msump4,msump5,msump6,msump7,msump8,msump9
user_id,,,,,,,
3,137734.573242,43075.747864,5297.908691,0.000000,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,10805.421875,10952.112305,0.000000,86198.161377,10038.188965,10772.799805,0.000000
37,0.000000,0.000000,5487.140625,5251.647949,0.000000,0.000000,0.000000
41,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...
562043,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
562205,319.916626,0.000000,0.000000,0.000000,0.000000,0.000000,1648.989708
562312,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
562721,0.000000,5607.572266,7369.252441,4826.499023,13006.508034,3581.332129,0.000000
562740,0.000000,467.072662,11404.376862,11880.058105,0.000000,443.030083,0.000000

In [24]:
msumm = transactions_upd.pivot_table(values="sm",
    index="user_id",
    columns="m",
    aggfunc='sum',
    fill_value=0,)
msumm.columns = list( map(lambda x: "msumm"+str(x), msumm.columns ) )
msumm

,msumm3,msumm4,msumm5,msumm6,msumm7,msumm8,msumm9
user_id,,,,,,,
3,0.000000,0.000000,-15144.601562,-153866.890625,-3390.320969,0.000000,0.000000
9,-13289.485764,-104223.187939,-109800.056656,-54146.384140,-18500.321304,-12387.577271,-11087.653740
13,-16394.193359,-27095.248047,-27650.769531,-76186.732422,-33908.388672,-53024.051758,-19224.679688
37,-32719.820328,-41364.700729,-67081.604048,-53322.076138,-69769.034760,-50056.823341,-28284.328693
41,-8045.445801,-17708.008820,-30354.633301,-17462.199585,-18175.117676,-16841.208984,0.000000
...,...,...,...,...,...,...,...
562043,0.000000,-142.056610,0.000000,-2984.231926,-11080.026783,-15374.940796,0.000000
562205,-10452.779190,-7546.495855,-6601.707232,-4821.073084,-6082.155629,-5607.360139,-1349.243835
562312,0.000000,-2644.634823,-1362.274536,-3165.544842,-3938.301605,-4495.630554,-2931.434910
562721,-20904.990967,-12082.776123,-27648.169678,-64254.888449,-30059.568512,-42680.736959,-764.794891
562740,-31250.922503,-36796.173475,-33804.052334,-26213.265722,-20043.419868,-14351.860060,-528.079102

In [25]:
data.head()

,user_id,report,employee_count_nm,bankemplstatus,customer_age,target,time,trans_sum,trans_std,trans_min,...,sin_day_of_week,cos_day_of_week,sin_month,cos_month,sin_week_of_year,cos_week_of_year,logsumabs_0,logsumabs_1,logsumabs_2,logsumabs_3
0,3,2,4,0,3,0.0,77.0,13706.416641,60860.880477,-153866.890625,...,0.974928,-0.222521,-5.000000e-01,-0.866025,-0.885456,-0.464723,0.00000,12.789712,0.0,0.0
1,9,1,6,0,3,NaN,NaN,-323434.666813,11797.055119,-90147.617188,...,-0.781831,0.623490,1.224647e-16,-1.000000,-0.464723,-0.885456,0.00000,12.686752,0.0,0.0
2,13,6,5,0,2,0.0,86.0,-124717.379150,23507.953991,-58740.300781,...,-0.974928,-0.222521,-5.000000e-01,0.866025,0.0,1.0,9.28478,12.825245,0.0,0.0
3,37,5,6,0,2,0.0,89.0,-331859.599463,3913.114835,-35782.984375,...,0.974928,-0.222521,-8.660254e-01,0.500000,-0.464723,0.885456,0.00000,12.775178,0.0,0.0
4,41,1,4,0,2,0.0,57.0,-108586.614166,5251.737982,-16841.208984,...,-0.781831,0.623490,1.224647e-16,-1.000000,-0.464723,-0.885456,0.00000,11.595303,0.0,0.0

In [26]:
data = data.join(msumm, on="user_id", how="left")

In [27]:
train_data = data[~data["target"].isna()]
train_data.reset_index(drop=True, inplace=True)

In [28]:
test_data = data[data["target"].isna()]
test_data.reset_index(drop=True, inplace=True)

In [29]:
train_user, val_user = train_test_split(train_data.index, test_size=0.2,
                                        stratify=train_data.target)
val_user.shape, train_user.shape

((12800,), (51199,))

In [30]:
train_data.iloc[train_user].target.value_counts(), train_data.iloc[val_user].target.value_counts()

(target
 0.0    46865
 1.0     4334
 Name: count, dtype: int64,
 target
 0.0    11717
 1.0     1083
 Name: count, dtype: int64)

In [31]:
transactions.head(3)

,user_id,mcc_code,currency_rk,transaction_amt,transaction_dttm,date
0,3,3,1,-183.883957,2022-01-28 12:05:33,2022-01-28
1,3,3,1,-3206.437012,2022-01-28 12:52:30,2022-01-28
2,3,16,1,-153866.890625,2022-02-16 14:45:56,2022-02-16

In [32]:
transactions.set_index("transaction_dttm", inplace=True)
transactions.drop(columns="date", inplace=True)
group_transactions = transactions.groupby("user_id")

In [33]:
group_transactions.get_group(3)

                     user_id  mcc_code  currency_rk  transaction_amt
transaction_dttm
2022-01-28 12:05:33        3         3            1      -183.883957
2022-01-28 12:52:30        3         3            1     -3206.437012
2022-02-16 14:45:56        3        16            1   -153866.890625
2022-03-09 19:58:29        3        56            1    -15144.601562
2022-03-12 18:11:31        3         0            1      5297.908691
2022-04-11 20:48:26        3         0            1       534.363098
2022-04-11 20:53:35        3         0            1      4549.455078
2022-04-29 18:42:58        3         0            1     37991.929688
2022-05-05 20:32:38        3         0            1     28335.613281
2022-05-14 20:14:31        3         0            1      5386.999023
2022-05-14 20:39:45        3         0            1    104011.960938

# Pytorch

## EarlyStoping

Class for stopping the model early

In [43]:
class EarlyStopping:
    """Early stops the training if validation loss doesn't improve after a given patience."""
    def __init__(self, patience=7, verbose=False, delta=0, path='checkpoint.pt', trace_func=print):
        self.patience = patience
        self.verbose = verbose
        self.counter = 0
        self.best_score = None
        self.early_stop = False
        self.val_loss_min = np.Inf
        self.delta = delta
        self.path = path
        self.result = {}
        self.trace_func = trace_func

    def __call__(self, val_loss, ci, model):

        score = -val_loss

        if self.best_score is None:
            self.best_score = score
            self.save_checkpoint(val_loss, ci, model)
        elif score < self.best_score + self.delta:
            self.counter += 1
            self.trace_func(f'EarlyStopping counter: {self.counter} out of {self.patience}')
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_score = score
            self.save_checkpoint(val_loss, ci, model)
            self.counter = 0

    def save_checkpoint(self, val_loss, ci, model):
        '''Saves model when validation loss decrease.'''
        if self.verbose:
            self.trace_func(f'Validation loss decreased ({self.val_loss_min:.6f} --> {val_loss:.6f}).  Saving model ...')
        self.result[self.path] = ci
        torch.save(model.state_dict(), self.path)
        self.val_loss_min = val_loss

## DataLoader

Class for data conversion

In [249]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, data,
                 transactions,
                 test=False):
        self.data = data
        self.transactions = transactions
        self.test = test

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        user_info = self.data.iloc[idx]

        # RNN input
        rnn_tensor = torch.from_numpy(self.transactions.get_group(user_info.user_id).drop(["user_id"], axis=1).to_numpy().astype(np.float32))
        rnn_tensor = torch.cat([rnn_tensor, torch.zeros(size=(1497-rnn_tensor.shape[0], rnn_tensor.shape[1]))]).to(torch.float32)

        # Linear input
        if not self.test:
            linear_input = torch.tensor(user_info.drop(["target", "time", "user_id"], axis=0).values).to(torch.float32)
        else:
            linear_input = torch.tensor(user_info.drop(["user_id"], axis=0).values).to(torch.float32)
            

        if self.test:
            return (rnn_tensor, linear_input)
        else:
            return (rnn_tensor, linear_input),\
                    torch.tensor([torch.tensor(user_info.time), torch.tensor(user_info.target)])

In [160]:
!mkdir ./models

mkdir: cannot create directory './models': File exists

## Model Training

### RNN

Implementation of the model

In [205]:
class RNN_big(nn.Module):
    def __init__(self,
                 input_rnn,
                 input_linear,
                 hidden_dim,
                 in1,
                 in2,
                 output_dim,
                 rnn_layers=2):
        super().__init__()
        self.batch_size = batch_size
        self.hidden_dim = hidden_dim
        self.rnn_layers = rnn_layers

        self.norm_rnn = nn.BatchNorm1d(1497)
        self.rnn1 = nn.GRU(input_rnn, hidden_dim, rnn_layers,
                            batch_first=True, bidirectional=True)

        self.fc1 = nn.Linear(hidden_dim*2, in2)
        self.fc2 = nn.Linear(hidden_dim*2, in2)

        self.norm1 = nn.BatchNorm1d(input_linear)
        self.linear1 = nn.Linear(input_linear, in1)
        self.linear2 = nn.Linear(in1, in2)

        self.out = nn.Linear(in2, output_dim)

    def forward(self, x1, x2, h):
        x1 = self.norm_rnn(x1)
        out_rnn, h = self.rnn1(x1, h)
        out_rnn = F.relu(out_rnn[:, -1])

        linear_1 = F.relu(self.fc1(out_rnn))
        linear_2 = F.relu(self.fc2(out_rnn))

        linear_features = F.relu(self.linear1(self.norm1(x2)))
        linear_features = F.relu(self.linear2(linear_features))
        hidden = linear_1 + linear_2 + linear_features

        out = self.out(hidden)
        return F.sigmoid(out), h

    def init_hidden(self, batch_size):
        weight = next(self.parameters()).data
        hidden = weight.new(self.rnn_layers*2, batch_size, self.hidden_dim).zero_().to(device)
        return hidden

### Train

In [221]:
batch_size = 64
val_dataset = CustomDataset(train_data.iloc[val_user], group_transactions)
val_loader = DataLoader(val_dataset, batch_size=batch_size, drop_last=True)

In [222]:
def train_model(model, loader, optimizer, criterion, epochs, path="./", patience=10):
    result = {}
    early_stop = EarlyStopping(patience=min(patience, epochs), path=path)

    for epoch in range(epochs):
        model.train()
        print("EPOCH ", epoch+1)

        epoch_loss = 0
        y_true, y_preds, times = [], [], []
        h = model.init_hidden(batch_size)

        for x, y in tqdm(loader):
            h = h.data
            x1, x2 = x
            time, y_batch = y[:, 0], y[:, 1]
            x1, x2, y_batch = x1.to(device), x2.to(device), y_batch.to(device)

            optimizer.zero_grad()
            predictions, h = model(x1, x2, h)

            loss = criterion(predictions, torch.unsqueeze(y_batch, -1).float())
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()

            times.extend(time)
            y_true.extend(y_batch.detach().cpu())
            y_preds.extend(predictions.detach().cpu())

        print("Loss:", epoch_loss / len(loader))
        print("CI:", concordance_index(np.array(times), -np.array(y_preds), np.array(y_true)))
        print("ROC_AUC:", roc_auc_score(y_true, y_preds), "\n")

        val_loss, ci = test(model, val_loader, criterion)
        early_stop(val_loss, ci, model)
        result.update(early_stop.result)

        if early_stop.early_stop:
              break

    return result


def test(model, loader, criterion=nn.BCELoss()):
    model.eval()
    loss, CI = 0, 0
    y_true, y_preds, times = [], [], []
    h = model.init_hidden(batch_size)

    with torch.no_grad():
        for x, y in tqdm(loader):
            x1, x2 = x
            time, y_batch = y[:, 0], y[:, 1]
            x1, x2, y_batch = x1.to(device), x2.to(device), y_batch.to(device)

            predictions, h = model(x1, x2, h)
            loss += criterion(predictions, torch.unsqueeze(y_batch, -1).float()).item()

            times.extend(time)
            y_true.extend(y_batch.detach().cpu())
            y_preds.extend(predictions.detach().cpu())

        val_loss = loss/len(loader)
        ci = concordance_index(np.array(times), -np.array(y_preds), np.array(y_true))
        print("Loss:", val_loss)
        print("CI:", ci)
        print("ROC_AUC:", roc_auc_score(y_true, y_preds), "\n")

    return val_loss, ci

In [223]:
train_dataset = CustomDataset(train_data.iloc[train_user], group_transactions)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, drop_last=True)

In [224]:
got_data = next(iter(train_loader))[0]
rnn_dim = got_data[0].shape[2]
linear_dim = got_data[1].shape[1]
hidden_dim = 16
in1 = 512
in2 = 128

model = RNN_big(rnn_dim, linear_dim, hidden_dim, in1, in2, 1, 4).to(device)
sum(p.numel() for p in model.parameters())

119863

In [225]:
optimizer = torch.optim.Adam(model.parameters(), lr=3e-4)
criterion = nn.BCELoss()

In [226]:
train_model(model, train_loader, optimizer, criterion, 100, path="./models/model.pt")

EPOCH  1

100%|██████████| 799/799 [02:32<00:00,  5.24it/s]

Loss: 0.27351657111892413
CI: 0.6888856304437417
ROC_AUC: 0.6834030708015219

100%|██████████| 200/200 [00:24<00:00,  8.01it/s]

Loss: 0.2651889868825674
CI: 0.7245874251901537
ROC_AUC: 0.715351836646818

EPOCH  2

100%|██████████| 799/799 [02:31<00:00,  5.26it/s]

Loss: 0.26065508752725597
CI: 0.7313859984310066
ROC_AUC: 0.7264504005955924

100%|██████████| 200/200 [00:25<00:00,  7.89it/s]

Loss: 0.2613238869607449
CI: 0.7296736989516505
ROC_AUC: 0.7240924019845998

EPOCH  3

100%|██████████| 799/799 [02:29<00:00,  5.33it/s]

Loss: 0.25648364039587884
CI: 0.7440509910344624
ROC_AUC: 0.7396973064567478

100%|██████████| 200/200 [00:25<00:00,  7.99it/s]

Loss: 0.2640709002315998
CI: 0.7375120235023174
ROC_AUC: 0.7290748240810856

EarlyStopping counter: 1 out of 10
EPOCH  4

100%|██████████| 799/799 [02:29<00:00,  5.35it/s]

Loss: 0.25403258415202473
CI: 0.7508212823327027
ROC_AUC: 0.7476761800354103

100%|██████████| 200/200 [00:24<00:00,  8.00it/s]

Loss: 0.2603545013442636
CI: 0.7356842649032592
ROC_AUC: 0.7310301397744956

EPOCH  5

100%|██████████| 799/799 [02:29<00:00,  5.33it/s]

Loss: 0.2521953866426578
CI: 0.7559881969932051
ROC_AUC: 0.7545512031020564

100%|██████████| 200/200 [00:25<00:00,  7.90it/s]

Loss: 0.2618442774936557
CI: 0.7392389548437804
ROC_AUC: 0.7320265532690741

EarlyStopping counter: 1 out of 10
EPOCH  6

100%|██████████| 799/799 [02:30<00:00,  5.29it/s]

Loss: 0.2504904841880625
CI: 0.7603053869376855
ROC_AUC: 0.758951120766661

100%|██████████| 200/200 [00:25<00:00,  7.84it/s]

Loss: 0.25874610524624586
CI: 0.7427902584784211
ROC_AUC: 0.7379818654950533

EPOCH  7

100%|██████████| 799/799 [02:33<00:00,  5.22it/s]

Loss: 0.2488717948633231
CI: 0.7652315837000405
ROC_AUC: 0.7641939130783009

100%|██████████| 200/200 [00:25<00:00,  7.79it/s]

Loss: 0.25629683539271353
CI: 0.7481186954392047
ROC_AUC: 0.743733308556965

EPOCH  8

100%|██████████| 799/799 [02:30<00:00,  5.31it/s]

Loss: 0.24789351084093575
CI: 0.7675875712956014
ROC_AUC: 0.7668858012823659

100%|██████████| 200/200 [00:25<00:00,  7.96it/s]

Loss: 0.26006623726338146
CI: 0.7380879918037853
ROC_AUC: 0.734097200435856

EarlyStopping counter: 1 out of 10
EPOCH  9

100%|██████████| 799/799 [02:29<00:00,  5.35it/s]

Loss: 0.2472265396775382
CI: 0.7691880545851726
ROC_AUC: 0.7684880834349518

100%|██████████| 200/200 [00:24<00:00,  8.07it/s]

Loss: 0.25652511350810525
CI: 0.746337667861299
ROC_AUC: 0.7406989126688963

EarlyStopping counter: 2 out of 10
EPOCH  10

100%|██████████| 799/799 [02:34<00:00,  5.16it/s]

Loss: 0.24574432640484487
CI: 0.7743147343421584
ROC_AUC: 0.7744485007042591

100%|██████████| 200/200 [00:26<00:00,  7.55it/s]

Loss: 0.25630883432924745
CI: 0.7464420930688922
ROC_AUC: 0.7423880636535167

EarlyStopping counter: 3 out of 10
EPOCH  11

100%|██████████| 799/799 [02:30<00:00,  5.31it/s]

Loss: 0.2450228051302281
CI: 0.7735567131671635
ROC_AUC: 0.7737258423514233

100%|██████████| 200/200 [00:25<00:00,  7.99it/s]

Loss: 0.25968020647764206
CI: 0.7428938794383676
ROC_AUC: 0.7357109348027674

EarlyStopping counter: 4 out of 10
EPOCH  12

100%|██████████| 799/799 [02:30<00:00,  5.33it/s]

Loss: 0.24369541631174624
CI: 0.7771550479151073
ROC_AUC: 0.7779573277106528

100%|██████████| 200/200 [00:25<00:00,  7.84it/s]

Loss: 0.25793328035622837
CI: 0.7445367880651681
ROC_AUC: 0.7378540039880183

EarlyStopping counter: 5 out of 10
EPOCH  13

100%|██████████| 799/799 [02:32<00:00,  5.23it/s]

Loss: 0.242631477351593
CI: 0.7794213783836081
ROC_AUC: 0.7803595933916954

100%|██████████| 200/200 [00:26<00:00,  7.69it/s]

Loss: 0.26061166793107987
CI: 0.7421231985487647
ROC_AUC: 0.7362890106640043

EarlyStopping counter: 6 out of 10
EPOCH  14

100%|██████████| 799/799 [02:33<00:00,  5.19it/s]

Loss: 0.24159655533497862
CI: 0.7843365151004398
ROC_AUC: 0.7861607797069897

100%|██████████| 200/200 [00:25<00:00,  7.83it/s]

Loss: 0.25905738908797504
CI: 0.740943748210549
ROC_AUC: 0.7351413699077923

EarlyStopping counter: 7 out of 10
EPOCH  15

100%|██████████| 799/799 [02:31<00:00,  5.28it/s]

Loss: 0.24044528828283424
CI: 0.7858194499149551
ROC_AUC: 0.7879358279899175

100%|██████████| 200/200 [00:25<00:00,  7.88it/s]

Loss: 0.26087953984737394
CI: 0.7454816097346812
ROC_AUC: 0.7411503091017455

EarlyStopping counter: 8 out of 10
EPOCH  16

100%|██████████| 799/799 [02:33<00:00,  5.21it/s]

Loss: 0.23940537509057339
CI: 0.7885285285547526
ROC_AUC: 0.7905351977054336

100%|██████████| 200/200 [00:24<00:00,  8.00it/s]

Loss: 0.2597883666306734
CI: 0.7425642225608904
ROC_AUC: 0.7384420881151369

EarlyStopping counter: 9 out of 10
EPOCH  17

100%|██████████| 799/799 [02:30<00:00,  5.31it/s]

Loss: 0.2385160260005051
CI: 0.7904274752901356
ROC_AUC: 0.7928392880447331

100%|██████████| 200/200 [00:25<00:00,  7.85it/s]

Loss: 0.25863066654652356
CI: 0.7416942805801623
ROC_AUC: 0.7373929539128813

EarlyStopping counter: 10 out of 10

{'./models/model.pt': 0.7481186954392047}

###Submmit

In [250]:
y_pred = []
test_dataset = CustomDataset(test_data.sort_values("user_id"), group_transactions, True)
test_loader = DataLoader(test_dataset, batch_size=128)

In [256]:
model.eval()
model.to(device)
h = model.init_hidden(128)
for x in tqdm(test_loader):
    x1, x2 = x
    predictions, _ = model(x1.to(device), x2.to(device), h)
    predictions = predictions.squeeze(0).to(torch.float).detach().cpu().numpy()
    y_pred.extend(predictions)

100%|██████████| 250/250 [00:55<00:00,  4.47it/s]

In [257]:
!wget https://storage.yandexcloud.net/ds-ods/files/data/docs/competitions/DataFusion2024/Data/sample_submit_naive.csv
submission = pd.read_csv("sample_submit_naive.csv")

--2024-04-25 12:14:15--  https://storage.yandexcloud.net/ds-ods/files/data/docs/competitions/DataFusion2024/Data/sample_submit_naive.csv
Resolving storage.yandexcloud.net (storage.yandexcloud.net)... 213.180.193.243, 2a02:6b8::1d9
Connecting to storage.yandexcloud.net (storage.yandexcloud.net)|213.180.193.243|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 788735 (770K) [text/csv]
Saving to: 'sample_submit_naive.csv'

sample_submit_naive 100%[===================>] 770.25K   809KB/s    in 1.0s

2024-04-25 12:14:17 (809 KB/s) - 'sample_submit_naive.csv' saved [788735/788735]

In [258]:
preds = []
for i in y_pred:
    preds.append(i[0])

In [259]:
submission.predict = preds

In [260]:
submission.head()

   user_id   predict
0        9  0.032000
1       61  0.006418
2       62  0.055881
3       80  0.008052
4       88  0.140380

In [ ]:
submission.to_csv("submission.csv", index=False)